name: Unit testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Cunit
      run: sudo apt-get -y install libcunit1-doc libcunit1-dev
    - name: make 
      run: make -C 3_Implementation/main/
